language: python
sudo: false
python:
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4
- 3.5
- pypy
- pypy3
install:
- pip install flake8 pytest pytest-sugar
- >
    if [[ "$TRAVIS_PYTHON_VERSION" != "3.2" ]]; then
      pip install codecov 'pytest-cov>=1.8.0';
      export PYTEST_COV="--cov monthday"
    fi
- pip install -e .
script:
- py.test $PYTEST_COV --doctest-glob='*.rst' --durations=5
- flake8 .
after_success:
- >
    if [[ "$TRAVIS_PYTHON_VERSION" != "3.2" ]]; then
      codecov
    fi
