language: python
sudo: false
python:
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4
- pypy
- pypy3
install:
- pip install codecov flake8 pytest pytest-cov pytest-sugar
- pip install -e .
script:
- py.test --cov monthday --doctest-glob='*.rst' --durations=5
- flake8 .
after_success:
- codecov
